# Production Configuration Template (YAML format)
# Copy this file to the same directory as the WAR file and rename it to application-prod.yml
# Then set the spring.profiles.active=prod environment variable or system property

spring:
  datasource:
    url: jdbc:mysql://your-db-server:3306/employeerating
    username: your_db_username
    password: your_db_password
  
  mail:
    username: your-email@gmail.com
    password: your-app-password
  
  jpa:
    show-sql: false

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN 